version: '3.8'

networks:
  app-tier:
    external:
      name: app-network

services:
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_ROUTE: ${API_ROUTE}
        API_ORIGIN: ${API_ORIGIN}
    ports:
      - "${NGINX_EXT_PORT}:80"
    env_file:
      - .env
    networks:
      - app-tier